<?php
include '../../backend/conn.php';
// [PRIORITY] PAGIDDELETE, MAGIINACTIVATE YUNG STATUS TAPOS YUN NA :> PAKIAGAWA MAMAYA PLS ANGE TYSM <3
// YUNG PAGE CONTENT MO RIN, DAPAT KAPAG INUUPDATE MO YUNG CATEGORY NAME, YUNG NASA CONTENT NUNG AUTOMATED NA PAGE IS NAGUUPDATE DIN!!
// WAG MO NA PAHIRAPAN SARILI MO, LAGAY MO NA YUNG SWAL ALERTS
// YUNG SA PRODUCT TABLE, KAPAG INACTIVE YUNG STATUS NUNG PRODUCT, INSTEAD NA MAHHIDE, MAPUPUNTA NALANG SIYA SA 
// + PINAKADULO THEN PWEDE SIYANG I-ACTIVATE ULIT IF GAGAMITIN SIYA
?>
